version: "3.0"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  # logstash:
  #   image: logstash:latest
  #   volumes:
  #     - $PWD/config-dir:/config-dir
  #     - $PWD/logs:/logs
  #   depends_on:
  #     - elasticsearch
  #   links:
  #     - elasticsearch
  #   command: logstash -f /config-dir/logstash.conf
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
    container_name: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  esdata1:
    driver: local
